---
- hosts: webserver
  remote_user: root
  vars:
    user: "demo"
    packages: ["php5", "apache2", "mysql-server", "git"]
    wp_repo: "https://github.com/WordPress/wordpress-develop.git"
    wp_version: "4.9"
    services: ["mysql", "apache2"]
  tasks:
    - name: Create user
      user:
        name: "{{ user }}"
        shell: /bin/bash

    - name: Install packages
      apt:
        name: "{{ item }}"
        state: present
      with_items: "{{ packages }}"
    - command: rm -Rf /var/www/html/
    - name: Install wordpress
      git:
        repo: "{{ wp_repo }}"
        dest: "/var/www/html/"
        version: "{{ wp_version }}"
        force: yes

    - name: Starting services
      service:
        name: "{{ item }}"
        state: started
      with_items: "{{ services }}"
