---
- hosts: webserver
  remote_user: admin
  vars:
    user: "demo"
    packages: ["php7", "apache2", "mysql"]
    wp_repo: "https://github.com/WordPress/wordpress-develop"
    wp_version: "4.9"
    services: ["mysqld", "apache2"]
  tasks:
    - name: Create user
      user:
        name: "{{ user }}"
        group: admin
        shell: /bin/bash

    - name: Install packages
      apt:
        name: "{{ item }}"
        state: present
      with_items: "{{ packages }}"

    - name: Install wordpress
      git:
        repo: "{{ wp_repo }}"
        dest: "/var/www/html"
        version: "{{ wp_version }}"
        force: yes

    - name: Starting services
      service:
        name: "{{ item }}"
        state: started
      with_items: "{{ services }}"
